version: 0.0
os: linux
files:
  - source: /
    destination: /srv/sislam_bootstrap
permissions:
  - object: /srv/sislam_bootstrap
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /srv/sislam_bootstrap/Gemfile.lock
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
  - object: /srv/sislam_bootstrap/scripts/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install_app.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/restart_app.sh
      timeout: 300
      runas: ec2-user
  Verify:
    - location: scripts/deploy_verify
      timeout: 300
      runas: ec2-user
