development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: bootstrap_development

test:
  adapter: async

sandbox:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: bootstrap_production
